### ISSUE TITLE
Issue in installing anaconda on the image  - vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/tensorflow-installer-tf-cpu-2.15.0:latest

### ISSUE THREAD

**Issue by vinayK34** [HabanaAI/Setup_and_Install#6]
Hi, I am trying to install the anaconda in **vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/tensorflow-installer-tf-cpu-2.15.0:latest** image but its failing with the below error - 

Step 10/35 : RUN bash /tmp/${ANACONDA_VERSION}-Linux-x86_64.sh -b
 ---> Running in 5d191472384b
PREFIX=/usr/anaconda3
Unpacking payload ...
entry_point.py:68: TqdmMonitorWarning: tqdm:disabling monitor support (monitor_interval = 0) due to:
can't start new thread
Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 726, in map
  File "concurrent/futures/_base.py", line 597, in map
  File "concurrent/futures/_base.py", line 597, in <listcomp>
  File "concurrent/futures/process.py", line 698, in submit
  File "concurrent/futures/process.py", line 658, in _start_executor_manager_thread
  File "threading.py", line 892, in start
RuntimeError: can't start new thread
[31] Failed to execute script entry_point
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "site-packages/tqdm/_monitor.py", line 44, in exit
  File "threading.py", line 1048, in join
RuntimeError: cannot join thread before it is started

To Reproduce the error I am following the below steps - 
# Install conda 
RUN wget -P /tmp https://repo.anaconda.com/archive/Anaconda3-2023.03-Linux-x86_64.sh
ENV HOME=/usr 
RUN bash /tmp/${ANACONDA_VERSION}-Linux-x86_64.sh -b  **--> failing at this step**
RUN source /usr/anaconda3/bin/activate

The issue is not only with the anaconda installation but GPG key is also expired and generating a new one having a lot of issue to update the apt packages

**Comment by vinayK34** [comment]
This is so unfortunate that no has yet responded to the issue, this tells how much behind the Habana Gaudi software support community from the NVIDIA
